import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.join(__dirname, 'public');
const dataFile = path.join(__dirname, 'data', 'store.json');
const PORT = Number(process.env.PORT || 8787);

const defaultState = {
  posts: [], jobs: [], audit: [],
  settings: { timezone: 'Asia/Riyadh', safeMode: true, brandName: 'Digital Insight AI', language: 'ar' },
  providers: {
    telegram: { connected: false, mode: 'ENV_REQUIRED' }, discord: { connected: false, mode: 'ENV_REQUIRED' },
    youtube: { connected: false, mode: 'NOT_CONFIGURED' }, instagram: { connected: false, mode: 'NOT_CONFIGURED' },
    facebook: { connected: false, mode: 'NOT_CONFIGURED' }, tiktok: { connected: false, mode: 'NOT_CONFIGURED' },
    x: { connected: false, mode: 'NOT_CONFIGURED' }, linkedin: { connected: false, mode: 'NOT_CONFIGURED' },
    pinterest: { connected: false, mode: 'NOT_CONFIGURED' }, threads: { connected: false, mode: 'NOT_CONFIGURED' },
    bluesky: { connected: false, mode: 'NOT_CONFIGURED' }
  }
};

function loadState(){if(!fs.existsSync(dataFile)){fs.writeFileSync(dataFile,JSON.stringify(defaultState,null,2));return structuredClone(defaultState)}return JSON.parse(fs.readFileSync(dataFile,'utf8'))}
function saveState(state){fs.writeFileSync(dataFile,JSON.stringify(state,null,2))}
function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body))}
function audit(state,action,detail={}){const row={id:crypto.randomUUID(),ts:new Date().toISOString(),action,detail};state.audit.unshift(row);state.audit=state.audit.slice(0,500);return row}
async function readBody(req){const chunks=[];for await(const c of req)chunks.push(c);const raw=Buffer.concat(chunks).toString('utf8');return raw?JSON.parse(raw):{}}
function refreshProviderState(state){state.providers.telegram.connected=Boolean(process.env.TELEGRAM_BOT_TOKEN&&process.env.TELEGRAM_CHAT_ID);state.providers.telegram.mode=state.providers.telegram.connected?'ENV_READY':'ENV_REQUIRED';state.providers.discord.connected=Boolean(process.env.DISCORD_WEBHOOK_URL);state.providers.discord.mode=state.providers.discord.connected?'ENV_READY':'ENV_REQUIRED'}
async function publishTelegram(content){if(!process.env.TELEGRAM_BOT_TOKEN||!process.env.TELEGRAM_CHAT_ID)return{ok:false,code:'MISSING_CREDENTIALS'};const url=`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`;const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:process.env.TELEGRAM_CHAT_ID,text:content})});const body=await r.json().catch(()=>({}));if(!r.ok||!body.ok)return{ok:false,code:'PROVIDER_ERROR',body};return{ok:true,providerId:String(body.result?.message_id||''),externalUrl:null}}
async function publishDiscord(content){if(!process.env.DISCORD_WEBHOOK_URL)return{ok:false,code:'MISSING_CREDENTIALS'};const r=await fetch(process.env.DISCORD_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content})});if(!r.ok)return{ok:false,code:'PROVIDER_ERROR',status:r.status};return{ok:true,providerId:`discord-${Date.now()}`,externalUrl:null}}
async function executeJob(state,job){const post=state.posts.find(p=>p.id===job.postId);if(!post){job.status='FAILED';job.error='POST_NOT_FOUND';return}job.status='PUBLISHING';job.updatedAt=new Date().toISOString();saveState(state);const results=[];for(const platform of job.platforms){let result;try{if(platform==='telegram')result=await publishTelegram(post.content);else if(platform==='discord')result=await publishDiscord(post.content);else result={ok:false,code:'NOT_IMPLEMENTED'}}catch(e){result={ok:false,code:'EXCEPTION',message:String(e?.message||e)}}results.push({platform,...result})}job.results=results;const okCount=results.filter(r=>r.ok).length;job.status=okCount===results.length&&okCount>0?'PUBLISHED':okCount>0?'PARTIAL_SUCCESS':'FAILED';job.updatedAt=new Date().toISOString();audit(state,'PUBLISH_ATTEMPT',{jobId:job.id,status:job.status,results});saveState(state)}
function staticFile(res,pathname){const target=pathname==='/'?path.join(publicDir,'index.html'):path.join(publicDir,pathname.replace(/^\//,''));if(!target.startsWith(publicDir)||!fs.existsSync(target)||fs.statSync(target).isDirectory())return false;const ext=path.extname(target);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream'});fs.createReadStream(target).pipe(res);return true}

const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);const state=loadState();refreshProviderState(state);try{if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,service:'Digital Insight Publisher',timezone:state.settings.timezone});if(req.method==='GET'&&u.pathname==='/api/state')return json(res,200,state);if(req.method==='POST'&&u.pathname==='/api/posts'){const b=await readBody(req);if(!b.content||!Array.isArray(b.platforms)||b.platforms.length===0)return json(res,400,{error:'content_and_platforms_required'});const post={id:crypto.randomUUID(),title:b.title||'',content:b.content,platforms:b.platforms,status:'DRAFT',createdAt:new Date().toISOString(),scheduledFor:b.scheduledFor||null,demo:false};state.posts.unshift(post);audit(state,'POST_CREATED',{postId:post.id});saveState(state);return json(res,201,post)}if(req.method==='POST'&&u.pathname==='/api/schedule'){const b=await readBody(req);const post=state.posts.find(p=>p.id===b.postId);if(!post)return json(res,404,{error:'post_not_found'});const job={id:crypto.randomUUID(),postId:post.id,platforms:post.platforms,status:'SCHEDULED',scheduledFor:b.scheduledFor||new Date().toISOString(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),results:[]};state.jobs.unshift(job);post.status='SCHEDULED';post.scheduledFor=job.scheduledFor;audit(state,'JOB_SCHEDULED',{jobId:job.id,postId:post.id});saveState(state);return json(res,201,job)}if(req.method==='POST'&&u.pathname==='/api/publish'){const b=await readBody(req);const post=state.posts.find(p=>p.id===b.postId);if(!post)return json(res,404,{error:'post_not_found'});if(state.settings.safeMode&&b.confirm!==true)return json(res,409,{error:'safe_mode_confirmation_required'});const job={id:crypto.randomUUID(),postId:post.id,platforms:post.platforms,status:'QUEUED',scheduledFor:new Date().toISOString(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),results:[]};state.jobs.unshift(job);audit(state,'JOB_QUEUED',{jobId:job.id});saveState(state);await executeJob(state,job);return json(res,200,job)}if(req.method==='POST'&&u.pathname==='/api/settings'){const b=await readBody(req);state.settings={...state.settings,...b};audit(state,'SETTINGS_UPDATED',{});saveState(state);return json(res,200,state.settings)}if(req.method==='POST'&&u.pathname==='/api/run-due'){const due=state.jobs.filter(j=>j.status==='SCHEDULED'&&new Date(j.scheduledFor)<=new Date());for(const job of due)await executeJob(state,job);return json(res,200,{processed:due.length})}if(req.method==='GET'&&staticFile(res,u.pathname))return;json(res,404,{error:'not_found'})}catch(e){console.error(e);json(res,500,{error:'internal_error'})}});
server.listen(PORT,()=>console.log(`Digital Insight Publisher listening on ${PORT}`));
